In [2]:
import numpy as np

In [ ]:
#Create a NumPy array

In [23]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
#Find the dimension

In [4]:
print(arr.ndim)

1


In [ ]:
#Find the shape

In [6]:
print(arr.shape)

(5,)


In [ ]:
#Create a 2D array with 3 rows and 3 columns.

In [15]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
print(arr2.ndim) # number of dimensions

2


In [17]:
print(arr2.shape) # shape

(2, 3)


In [ ]:
#Find the value at row 2, column 3

In [18]:
print(arr2[1,2])

6


In [ ]:
#Print the first three elements

In [24]:
print(arr[0:3])

[10 20 30]


In [ ]:
#Print every second element

In [27]:
print(arr[::2])

[10 30 50]


In [ ]:
#Multiply every value by 5

In [28]:
print(arr*5)

[ 50 100 150 200 250]


In [ ]:
#Add 100 to every value

In [29]:
print(arr+100)

[110 120 130 140 150]


In [ ]:
#Find the total

In [33]:
print(np.sum(arr))

150


In [ ]:
#Find the average

In [34]:
print(np.mean(arr))

30.0


In [ ]:
#Find the minimum

In [35]:
print(np.min(arr))

10


In [ ]:
#Find the maximum

In [36]:
print(np.max(arr))

50


In [ ]:
#Find the median

In [37]:
print(np.median(arr))

30.0


In [ ]:
#Find the standard deviation

In [40]:
print(np.std(arr))

14.142135623730951


In [ ]:
#Find values greater than 25

In [41]:
print(arr[arr>25])

[30 40 50]


In [ ]:
#Find values less than 30

In [42]:
print(arr[arr<30])

[10 20]


In [ ]:
#Find values between 20 and 50.

In [46]:
print(arr[(arr>20) & (arr<50)])

[30 40]


In [ ]:
#Create an array containing a missing value.

In [47]:
arr3 = np.array([10, 20, np.nan, 40, 50])

print(arr3)

[10. 20. nan 40. 50.]


In [ ]:
#Calculate the mean while ignoring the missing value

In [48]:
print(np.nanmean(arr3))

30.0


In [ ]:
#Detect the missing value

In [49]:
print(np.isnan(arr3))

[False False  True False False]


In [ ]:
#Create sales data and calculate total sales

In [50]:
sales = np.array([10000,15000,20000,25000,30000])

print(np.sum(sales))

100000


In [ ]:
#Find sales above ₹20,000

In [52]:
print(sales[sales>20000])

[25000 30000]


In [ ]:
#Increase all sales by 10%.

In [53]:
new_sales = sales * 1.10

print(new_sales)

[11000. 16500. 22000. 27500. 33000.]


In [ ]:
#Classify sales as High or Low where sales ≥ ₹20,000 is High

In [57]:
print(np.where(new_sales>=20000,"high","low"))

['low' 'low' 'high' 'high' 'high']


In [ ]:
#Mini Data Analyst Project

In [58]:
sales = np.array([12000,15000,18000,22000,25000,19000,30000,28000,17000,35000])

print("Sales Data:", sales)

print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
print("Minimum Sales:", np.min(sales))
print("Maximum Sales:", np.max(sales))
print("Median Sales:", np.median(sales))
print("Standard Deviation:", np.std(sales))

high_sales = sales[sales > 20000]

print("High Value Sales:", high_sales)
print("Number of High Value Sales:", len(high_sales))
print("Average High Value Sales:", np.mean(high_sales))

increased_sales = sales * 1.10

print("Sales After 10% Increase:", increased_sales)

Sales Data: [12000 15000 18000 22000 25000 19000 30000 28000 17000 35000]
Total Sales: 221000
Average Sales: 22100.0
Minimum Sales: 12000
Maximum Sales: 35000
Median Sales: 20500.0
Standard Deviation: 6905.794668247819
High Value Sales: [22000 25000 30000 28000 35000]
Number of High Value Sales: 5
Average High Value Sales: 28000.0
Sales After 10% Increase: [13200. 16500. 19800. 24200. 27500. 20900. 33000. 30800. 18700. 38500.]
